# Generated by Django 3.1.1 on 2021-04-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheeseModel',
            new_name='Cheese',
        ),
    ]
